### ISSUE TITLE
群晖上执行失败 已设置环境变量

### ISSUE THREAD

**Issue by xiaotiantian1132** [TreviD/aliddns#10]
报错内容：Traceback (most recent call last):
File "/volume1/homes/xiaotiantian/aliddns.py", line 320, in
print("本机IP: " + ip)
TypeError: Can't convert 'NoneType' object to str implicitly
已设置环境变量 依旧复现

**Comment by xiaotiantian1132** [comment]
已解决 卸载 pip install requests即可

**Comment by Hope-you** [comment]
同样的问题，是用pip卸载 requests包吗？还是安装？

**Comment by xiaotiantian1132** [comment]
第一次是这样干的，后来还出现这个问题 此方法无效了 ，查log发现是ipv6问题 群晖里面ipv6网卡是ovs_eth1 修改252行改成ovs_eth1解决问题 之后没出现过类似问题 你用作者更新过的脚本试一下 可能已经解决ipv6获取的问题
