### ISSUE TITLE
群晖开启了ipv6后，ipv4 获取错误

### ISSUE THREAD

**Issue by GooeyNyan** [TreviD/aliddns#8]
get_ipv4_net 调用了 "https://api.ip.sb/jsonip"，开启 ipv6 后会获取到 ipv6 的地址，逻辑有点问题。

建议改成 "https://api-ipv4.ip.sb/jsonip" 吧。

![Y8zP8x.png](https://s1.ax1x.com/2020/05/11/Y8zP8x.png)

**Comment by TreviD** [comment]
已修改！多谢🙏！！
