### ISSUE TITLE
时区不同，查询信息失败时报错

### ISSUE THREAD

**Issue by samuelgaocn** [TreviD/aliddns#9]
ubuntu@ip-172-31-30-120:~$ date
Mon May 18 09:22:24 UTC 2020
ubuntu@ip-172-31-30-120:~$ python3 aliddns.py aws samuelgao.win A
开始处理: RR:aws DomainName:samuelgao.win
本机IP: 31.41.50.135
查询域名信息：aws samuelgao.win A
HTTP Error 400: Bad Request
查询域名信息失败：{"RequestId":"82CE4CB5-7164-4EFC-9667-B683493D2CC3","Message":"Specified time stamp or date value is expired.","Recommend":"https://error-center.aliyun.com/status/search?Keyword=InvalidTimeStamp.Expired&source=PopGw","HostId":"alidns.aliyuncs.com","Code":"InvalidTimeStamp.Expired"}
Traceback (most recent call last):
  File "aliddns.py", line 319, in <module>
    if recordListInfo['TotalCount'] == 0:
TypeError: 'NoneType' object is not subscriptable
ubuntu@ip-172-31-30-120:~$
不同的时区，查询信息失败时报错

**Comment by TreviD** [comment]
已修复
